FROM tomcat:8-jre8

ARG FILE_NAME_CONFIGURATION
ARG PATH_NAME_CONFIGURATION
RUN mkdir $PATH_NAME_CONFIGURATION
COPY $FILE_NAME_CONFIGURATION $PATH_NAME_CONFIGURATION

ARG URL_WAR
ADD $URL_WAR /usr/local/tomcat/webapps/